### PR TITLE
added the house of lore

### PR DESCRIPTION
**Pull request by degrigis**
Signed-off-by: degrigis <fbi.gritti@gmail.com>

### CODE REVIEW

**Comment by zardus** [comment]
Wow, thanks! Looks like pretty l337 stuff :-)

**Comment by degrigis** [comment]
:-)
Time permitting, PoCs for the missing houses of Malloc Maleficarum will come!

**Comment by antoniobianchi333** [comment]
Do you know any CTF challenge in which this is useful?

**Comment by degrigis** [comment]
not yet in my knowledge.

**Pull request merged**
