### PR TITLE
House of Einherjar: Fix formatting and grammar

### PR DESCRIPTION
**Pull request by Grazfather**

### CODE REVIEW

**Comment by zardus** [comment]
Thanks! Would you mind pushing a fixup that keeps the line spacing like it was? Otherwise, there are tons of "misleading" line changes in here :-)

**Comment by Grazfather** [comment]
Sure. That'll mean there's mixed tabs and spaces, though.

**Comment by salls** [comment]
Thanks!

**Comment by Grazfather** [comment]
:beer:

**Pull request merged**
