### PR TITLE
updated glibc version for hof, fastbin_dup, and tcache_dup

### PR DESCRIPTION
**Pull request by cyanboy**
House of Force, fastbin_dup, and tcahce_dup no longer work as of glibc version 2.28

### CODE REVIEW

**Comment by Kyle-Kyle** [comment]
Tcache_dup still works on 2.28

**Comment by Kyle-Kyle** [comment]
hm. Not sure about others. But I'm sure tcache_dup does not work on 2.28. So, tcache_dup should be 2.25 - 2.27

**Comment by cyanboy** [comment]
I just did some testing.  On ubuntu:18.10 with glibc 2.28, and tcache_dup works.
On ubuntu:19.04 with glibc 2.29 tcache_dup does not work.

**Comment by m1ghtym0** [comment]
@cyanboy Have you tested the others as well?

**Comment by cyanboy** [comment]
@m1ghtym0 I've tested House of Force, Fastbin Dup Into Stack, Fastbin Dup, Fastbin Dup Consolidate, tcache Dup. These do no longer work. 

tcache poisoning, House of Spirit, and tcache House of Spirit still work.

**Comment by m1ghtym0** [comment]
Ok great, thanks! I'm assuming you've tested them without tcache enabled when necessary?

**Comment by cyanboy** [comment]
My mistake. I completely forgot to test without tchache enabled. I did so, and it turns out that fastbin attacks still work (when tchache is disabled)! When tcache is enabled, the tcache double free protection will be triggered when trying to do fastbin_dup. Now it should be corrected.

**Comment by m1ghtym0** [comment]
Ok perfect, thanks!

**Pull request merged**
