### PR TITLE
add doc for usage/installation

### PR DESCRIPTION
**Pull request by martinclauss**
To quickly start with how2heap, I created some opinionated setup instructions... maybe you and others find them useful :) 

Best
Martin

### CODE REVIEW

**Comment by ffreeez** [comment]
## English

### Installation

**Recommended Linux version: Ubuntu 18.04**

Get the repo

```bash
$ git clone https://github.com/ffreeez/how2heap_zh
$ cd ./how2heap_zh
$ git submodule update --init --recursive
```

Patchelf installation

```bash
$ sudo apt install patchelf
```

### Compile

Use `make` in the root directory to compile the project

```bash
$ cd ./how2heap_zh
$ make
```

### Run
Using glibc_run.sh to execute executable files is a more convenient replacement for glibc

Before you can use this script, you need to install patchelf and update the downloadable list in the glibc-all-in-one project

```bash
$ cd ./how2heap_zh/glibc-all-in-one
$ chmod +x ./*
$ ./update_list
```

When you run the `update_list` program, you might be prompted `-bash:./update_list: /usr/bin/python: bad interpreter: No such file or directory`

In a text editor, change the first line in the `update_list` file to `#!/usr/bin/python` changed to `#!/usr/bin/python3` will do

```
Usage: ./glibc_run.sh <version> <target> [-h] [-i686] [-u] [-r] [-gdb | -r2 | -p]"
-i686 - use x32 bits libc
-u - update libc list in glibc-all-in-one
-r - download libc in glibc-all-in-one
-gdb - start target in GDB
-r2 - start target in radare2
-p - just set interpreter and rpath in target without execution
```

And here's an example

```bash
$ ./glibc_run.sh 2.23 ./first_fit
```

## 简体中文/Simplified Chinese

### 安装

建议使用的Linux版本: Ubuntu 18.04

获取仓库

```bash
$ git clone https://github.com/ffreeez/how2heap_zh
$ cd ./how2heap_zh
$ git submodule update --init --recursive
```

patchelf 安装

```bash
$ sudo apt install patchelf
```

### 编译

在根目录下直接make即可

```bash
$ cd ./how2heap_zh
$ make
```

### 执行

使用glibc_run.sh来执行可执行文件，可以更方便的替换glibc
在使用这个脚本之前，需要安装`patchelf`，并且要在`glibc-all-in-one`项目中更新可下载的列表

```bash
$ cd ./how2heap_zh/glibc-all-in-one
$ chmod +x ./*
$ ./update_list
```

执行`update_list`时，可能会提示`-bash: ./update_list: /usr/bin/python: bad interpreter: No such file or directory`
，在文本编辑器中把`update_list`文件中的第一行`#!/usr/bin/python`改为`#!/usr/bin/python3`即可

```
[用法] ./glibc_run.sh <glibc版本号> <可执行文件> [-h] [-i686] [-u] [-r] [-gdb | -r2 | -p]
-i686 -使用32位的libc
-u 在glibc-all-in-one中更新libc列表
-r 在glibc-all-in-one中下载libc
-gdb -在gdb中执行目标文件
-r2 -在radare2中执行目标文件
-p -只在可执行文件中修改interpreter和rpath来指向对应的glibc并且不执行
```

这是一个执行示例

```bash
$ ./glibc_run.sh 2.23 ./first_fit
```

**Comment by Kyle-Kyle** [comment]
This guide looks great. But I have one small request, can you please move the Quick Setup before Complete Setup? It's like the TLDR section before the long discussion :D

**Comment by martinclauss** [comment]
You are right :D This makes more sense.. I changed the sequence ;)

Thanks!

**Comment by Kyle-Kyle** [comment]
Thank you for your contribution!

**Pull request merged**
